### ISSUE TITLE
Use settings_type::STEP instead of SETTINGS_TYPE_STEP

### ISSUE THREAD

**Issue by schach** [uniwue-rz/moodle-lifecyclestep_movecategory#2]
While testing this plugin, I noticed that it causes the task \tool_lifecycle\task\lifecycle_task to fail.

Apparently there were changes made to moodle-tool_lifecycle which are missing in movecategorystep.
https://github.com/learnweb/moodle-tool_lifecycle/commit/1e64cedaa67866bd61a7928350318a1ec77b0d50

The respective changes (use settings_type::STEP instead of SETTINGS_TYPE_STEP in lib.php) fixed the issue.

Cheers,
 Heiko

**Comment by sus16cn** [comment]
Hi Heiko,

thanks, I have created a pull request, because I lack the rights

**Comment by yorickreum** [comment]
Hi Susi,

ich habe offenbar noch Admin-Zugriff auf das Repository und habe Dich nun auch dort als Admin eingetragen. Ich denke, Du solltest eine Mail bekommen habe, über die Du Zugang bekommst?

Viele Grüße
Yorick




—
Yorick Reum
Zweierweg 57
D-97074 Würzburg
+49 151 52 18 85 01
mail@yorickreum.de

**Comment by yorickreum** [comment]
Hi Susi nochmal,

mir fällt gerade aber noch die Beschreibung des Repos auf GitHub auf… “(Mirror Only) Step for moodle-tool_lifecycle to move courses to a selectable category”…
Ich glaube, die Idee war, dass wir das Repository intern im Phabricator verwalten und es dann vom Phabricator automatisch auf GitHub rüber gespiegelt wird…

Viele Grüße
Yorick

**Comment by sus16cn** [comment]
Jetzt wo du es schreibst, kommt mir das bekannt vor. Ich blick jetzt auch nicht mehr durch, irgendwie ist es jetzt auch
trotzdem nicht drinnen, obwohl  ich den pull-request jetzt angenommen haben.

 

Ich hätte nicht gedacht, dass ich nicht genügend Rechte habe , ich habe jetzt nämlich ewig mit token und ssh key
rumgemacht, damit ich pushen kann und das ging eben nicht. Daher dann den Pull-request.

 

Was soll ich denn jetzt machen, wenn wir das als Mirror eingestellt haben.

 

Von: Yorick Reum
Gesendet: Sonntag, 7. Februar 2021 16:26
An: uniwue-rz/moodle-lifecyclestep_movecategory
Cc: Susanne Schenk; Comment
Betreff: Re: [uniwue-rz/moodle-lifecyclestep_movecategory] Use settings_type::STEP instead of SETTINGS_TYPE_STEP (#2)

 


Hi Susi nochmal,

mir fällt gerade aber noch die Beschreibung des Repos auf GitHub auf… “(Mirror Only) Step for moodle-tool_lifecycle to
move courses to a selectable category”…
Ich glaube, die Idee war, dass wir das Repository intern im Phabricator verwalten und es dann vom Phabricator
automatisch auf GitHub rüber gespiegelt wird…

Viele Grüße
Yorick



> On 7. Feb 2021, at 16:17, Yorick Reum <yorick.reum@stud-mail.uni-wuerzburg.de> wrote:
> 
> Hi Susi,
> 
> ich habe offenbar noch Admin-Zugriff auf das Repository und habe Dich nun auch dort als Admin eingetragen. Ich denke,
Du solltest eine Mail bekommen habe, über die Du Zugang bekommst?
> 
> Viele Grüße
> Yorick
> 
> 
> 
> 
> —
> Yorick Reum
> Zweierweg 57
> D-97074 Würzburg
> +49 151 52 18 85 01
> mail@yorickreum.de <mailto:mail@yorickreum.de>
> 
> 
> 
>> On 7. Feb 2021, at 16:14, sus16cn <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> 
>> Hi Heiko,
>> 
>> thanks, I have created a pull request, because I lack the rights
>> 
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
<https://github.com/uniwue-rz/moodle-lifecyclestep_movecategory/issues/2#issuecomment-774690699>, or unsubscribe

**Comment by yorickreum** [comment]
Hast Du schon probiert, es in den Phabricator zu pushen, und geschaut, ob der direkt spiegelt? (Eventuell ein paar Minuten warten…)

**Comment by sus16cn** [comment]
Hi Heiko,
i close the issue, its fixed :)

**Comment by schach** [comment]
Thank you for fixing this.
Forgot to mention, in order for settings_type::STEP to work, This line has to be added (line 31):
use tool_lifecycle\settings_type;
